name: Demo 01 Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Ciao bella ciao!"
      - name: Print goodbye
        run: echo "Bella ciao bella ciao bella ciao ciao ciao"
